### ISSUE TITLE
ERY UPDATE.

### ISSUE THREAD

**Issue by Ery-man-thus** [SkyblockClient/SkyblockClient-REPO#414]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et. Nam at lectus urna duis convallis convallis tellus id interdum. Diam volutpat commodo sed egestas egestas fringilla. Enim blandit volutpat maecenas volutpat blandit.

hey guys, ery here. parents cracked down on my internet use so i had to deactivate my discord account yesterday. forgot the password to my main GitHub account + it has authy 2FA so i had to resort to this account right now. not sure when I'll be back, but the Discord accounts are *deactivated* and not *deleted*.

DeDiamondPro, it was a pleasure working with you on the Skyguide/SBH thing a few weeks back. Good luck on the Crystal Hollows.

nea89, please continue SBHUD if you're comfortable doing so. (I can't log into my usual GitHub account at this immediate moment to invite you to the repo.)

Desco, good luck with your Kotlin rewrite of Synthesis.

KTibow, please update SBHUD one last time whenever DeDiamondPro finishes his Crystal Hollows map for Skyguide. The release notes and .jar file have been finished for a while now.

All SkyClient crew + Polyfrost folks, good luck with your future endeavors. OneConfig is looking good so far, even though I never had an opportunity to use it myself.

Erymanthus.

**Comment by KTibow** [comment]
welp
gl

**Comment by My-Name-Is-Jeff** [comment]
💀

**Comment by UnderscoreRayless** [comment]
You could've just said you forgot your mac on the subway again. We wouldn't have judged you.

**Comment by Shiggy-dev** [comment]
ery moment

**Comment by My-Name-Is-Jeff** [comment]
Local Nav Open Menu
BuyMacBook Pro 14-inch and 16-inch
MacBook Pro 14- and 16-inch - Technical Specifications
 Model 1Model 2
14-inch
16-inch

Finish

Silver
Space Gray
Price
Chip

Apple M1 Pro chip

8-core CPU with 6 performance cores and 2 efficiency cores

14-core GPU

16-core Neural Engine

200GB/s memory bandwidth

Media engine

Hardware-accelerated H.264, HEVC, ProRes, and ProRes RAW

Video decode engine

Video encode engine

ProRes encode and decode engine

Configurable to:

M1 Pro with 10-core CPU and 14-core GPU, M1 Pro with 10-core CPU and 16-core GPU, M1 Max with 10-core CPU and 24-core GPU, or M1 Max with 10-core CPU and 32-core GPU


Apple M1 Pro chip

10-core CPU with 8 performance cores and 2 efficiency cores

16-core GPU

16-core Neural Engine

200GB/s memory bandwidth

Media engine

Hardware-accelerated H.264, HEVC, ProRes, and ProRes RAW

Video decode engine

Video encode engine

ProRes encode and decode engine

Configurable to:

M1 Max with 10-core CPU and 24-core GPU or M1 Max with 10-core CPU and 32-core GPU

Display
Liquid Retina XDR display

14.2-inch (diagonal) Liquid Retina XDR display;1 3024-by-1964 native resolution at 254 pixels per inch


XDR (Extreme Dynamic Range)

1,000,000:1 contrast ratio

XDR brightness: 1000 nits sustained full-screen, 1600 nits peak2 (HDR content only)

SDR brightness: 500 nits

Color

1 billion colors

Wide color (P3)

True Tone technology

Refresh rates

ProMotion technology for adaptive refresh rates up to 120Hz

Fixed refresh rates: 47.95Hz, 48.00Hz, 50.00Hz, 59.94Hz, 60.00Hz

Memory
16GB

16GB unified memory

Configurable to:

32GB (M1 Pro or M1 Max) or 64GB (M1 Max)

Battery and Power3
Up to 17 hours Apple TV app movie playback

Up to 11 hours wireless web

70-watt-hour lithium-polymer battery3

67W USB-C Power Adapter (included with M1 Pro with 8-core CPU)

96W USB-C Power Adapter (included with M1 Pro with 10-core CPU or M1 Max, configurable with M1 Pro with 8-core CPU)

USB-C to MagSafe 3 Cable

Fast-charge capable with 96W USB-C Power Adapter

Storage4
512GB

512GB SSD
Configurable to:

1TB, 2TB, 4TB, or 8TB
1TB

1TB SSD
Configurable to:

2TB, 4TB, or 8TB
Charging and Expansion
SDXC card slot

HDMI port

3.5 mm headphone jack

MagSafe 3 port

Three Thunderbolt 4 (USB-C) ports with support for:

Charging

DisplayPort

Thunderbolt 4 (up to 40Gb/s)

USB 4 (up to 40Gb/s)

SDXC Thunderbolt 4 HDMIMagSafe 3Thunderbolt 4Headphone jack

Display Support
Simultaneously supports full native resolution on the built-in display at 1 billion colors and:

Up to two external displays with up to 6K resolution at 60Hz at over a billion colors (M1 Pro) or Up to three external displays with up to 6K resolution and one external display with up to 4K resolution at 60Hz at over a billion colors (M1 Max)

Thunderbolt 4 digital video output

Native DisplayPort output over USB‑C

VGA, HDMI, DVI, and Thunderbolt 2 output supported using adapters (sold separately)

HDMI digital video output

Support for one display with up to 4K resolution at 60Hz

DVI output using HDMI to DVI Adapter (sold separately)

Video Playback
Supported formats include HEVC, H.264, and ProRes

HDR with Dolby Vision, HDR10, and HLG

Audio Playback
Supported formats include AAC, MP3, Apple Lossless, FLAC, Dolby Digital, Dolby Digital Plus, and Dolby Atmos

Keyboard and Trackpad
Backlit Magic Keyboard with:

78 (U.S.) or 79 (ISO) keys including 12 full-height function keys and 4 arrow keys in an inverted-T arrangement

Touch ID

Ambient light sensor

Force Touch trackpad for precise cursor control and pressure-sensing capabilities; enables Force clicks, accelerators, pressure-sensitive drawing, and Multi-Touch gestures

**Comment by ghost** [comment]
skyclient poppin offff rn brah

guess it's time for a resurface from me :trollgod:

**Comment by ghost** [comment]
it is time.

see you soon, friends
