### ISSUE TITLE
Changing install folder crashes installer

### ISSUE THREAD

**Issue by cryolithic** [SkyblockClient/SkyblockClient-REPO#492]
Run the installer
Choose Advanced Settings
Click Select Folder
Observe application terminates.

**Comment by KTrain5169** [comment]
Incorrect repo, please comment at [SkyblockClient/SkyClient-Windows](https://github.com/SkyblockClient/SkyClient-Windows)

**Comment by cryolithic** [comment]
Thanks! Sorry about that
